name: Container Build

on:
  pull_request:
    types: [opened, synchronized, repoened]
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

defaults:
  run:
    shell: bash

jobs:
  container-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v1
    
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          tags: |
            ghcr.io/kmorris896/activity-monitor:latest
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
