name: Testing Suite
# This workflow doesn't actually test anything yet.  It creates a release 
# when there is a push to main.

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    types: [ opened, synchronize, reopened, labeled ]
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  tag-dry-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create Tag -- Dry Run
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.TAGACTION_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          VERBOSE: true
          DRY_RUN: true

